# Generated by Django 4.2.7 on 2024-01-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='timestamp',
        ),
    ]
