# Generated by Django 4.2.7 on 2024-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='return_book',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
