# Generated by Django 4.2.7 on 2024-01-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_return_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='return_book',
        ),
    ]
